# Generated by Django 5.2.6 on 2025-12-06 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 6, 7, 42, 20, 598706, tzinfo=datetime.timezone.utc)),
        ),
    ]
