# Generated by Django 5.2.6 on 2025-12-06 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_alter_issue_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 6, 7, 47, 51, 879412, tzinfo=datetime.timezone.utc)),
        ),
    ]
